/*
Constants for identifying the raw inputs from hardware/OS Layer.

Author : Romesh Selvanathan

Date : October 2012
*/

#ifndef __RAWINPUTCONSTANTS_H__
#define __RAWINPUTCONSTANTS_H__

enum RawInputAxis {
	AXIS_MOUSE_X,
	AXIS_MOUSE_Y
};

enum RawInputButton
{
	BUTTON_LBUTTON,		// Left Mouse Button
	BUTTON_RBUTTON,		// Right Mouse Button
	BUTTON_MBUTTON,		// Middle Mouse Button
	BUTTON_BACK,		// Backspace key
	BUTTON_TAB,			
	BUTTON_CLEAR,		
	BUTTON_RETURN,
	BUTTON_SHIFT,
	BUTTON_CONTROL,
	BUTTON_ALT,			// ALT Key
	BUTTON_PAUSE,		// Pause Key
	BUTTON_CAPSLOCK,
	BUTTON_ESCAPE,
	BUTTON_SPACEBAR,
	BUTTON_PAGEUP,
	BUTTON_PAGEDOWN,
	BUTTON_END,
	BUTTON_HOME,
	BUTTON_LEFT,
	BUTTON_UP,
	BUTTON_RIGHT,
	BUTTON_DOWN,
	BUTTON_SELECT,
	BUTTON_PRINTSCREEN,
	BUTTON_INSERT,
	BUTTON_DELETE,
	BUTTON_0,
	BUTTON_1,
	BUTTON_2,
	BUTTON_3,
	BUTTON_4,
	BUTTON_5,
	BUTTON_6,
	BUTTON_7,
	BUTTON_8,
	BUTTON_9,
	BUTTON_A,
	BUTTON_B,
	BUTTON_C,
	BUTTON_D,
	BUTTON_E,
	BUTTON_F,
	BUTTON_G,
	BUTTON_H,
	BUTTON_I,
	BUTTON_J,
	BUTTON_K,
	BUTTON_L,
	BUTTON_M,
	BUTTON_N,
	BUTTON_O,
	BUTTON_P,
	BUTTON_Q,
	BUTTON_R,
	BUTTON_S,
	BUTTON_T,
	BUTTON_U,
	BUTTON_V,
	BUTTON_W,
	BUTTON_X,
	BUTTON_Y,
	BUTTON_Z,	
	BUTTON_NUMPAD0,
	BUTTON_NUMPAD1,
	BUTTON_NUMPAD2,
	BUTTON_NUMPAD3,
	BUTTON_NUMPAD4,
	BUTTON_NUMPAD5,
	BUTTON_NUMPAD6,
	BUTTON_NUMPAD7,
	BUTTON_NUMPAD8,
	BUTTON_NUMPAD9,
	BUTTON_MULTIPLY,
	BUTTON_ADD,
	BUTTON_SEPARATOR,
	BUTTON_SUBTRACT,
	BUTTON_DECIMAL,
	BUTTON_DIVIDE,
	BUTTON_F1,
	BUTTON_F2,
	BUTTON_F3,
	BUTTON_F4,
	BUTTON_F5,
	BUTTON_F6,
	BUTTON_F7,
	BUTTON_F8,
	BUTTON_F9,
	BUTTON_F10,
	BUTTON_F11,
	BUTTON_F12,
	BUTTON_NUMLOCK,
	BUTTON_LSHIFT,
	BUTTON_RSHIFT,
	BUTTON_LCONTROL,
	BUTTON_RCONTROL,
	BUTTON_NULL = 99999
};

#endif 
